[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "java -jar app.jar --spring.profiles.active=prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
sleepApplication = false
useLegacyStacker = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.multiRegionConfig.asia-southeast1-eqsg3a]
numReplicas = 1
