# ===========================================
# Railway Production Deployment Configuration
# ===========================================

[build]
# Use Dockerfile to build the backend
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
buildContext = "backend"

[deploy]
# The startCommand is handled by the Dockerfile's ENTRYPOINT, so we remove it here for cleanliness.
# startCommand = "java -jar app.jar"

[[services]]
# Public HTTP port
port = 8080
protocol = "tcp"
authentication = "public"

# Healthcheck for Railway to verify deployment
healthcheckPath = "/health"
healthcheckTimeout = 300

# Optional: Replicas and region
region = "asia-southeast1"

# Resource limits (if needed)
cpu = 2
memory = 1024